name: Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**.c'
  workflow_dispatch:

env:
  BUILD_DIR: build
  OUTPUT_NAME: EveningStudyManager
  ZIP_NAME: EveningStudyManager-${{ github.run_number }}.zip

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Create build directory
      run: mkdir "$Env:BUILD_DIR"

    - name: Compile program
      run: cl /nologo /Fe:"$Env:BUILD_DIR\$Env:OUTPUT_NAME.exe" /W4 /sdl main.c
      shell: cmd

    - name: Verify executable
      run: dir "$Env:BUILD_DIR\$Env:OUTPUT_NAME.exe"
      shell: cmd

    - name: Copy config file
      run: copy config.ini "$Env:BUILD_DIR"
      shell: cmd

    - name: Create ZIP package
      run: Compress-Archive -Path "$Env:BUILD_DIR\*" -DestinationPath "$Env:ZIP_NAME"
      shell: powershell

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: ${{ env.ZIP_NAME }}

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write
      
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: release-package

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Build v${{ github.run_number }}"
        tag_name: v${{ github.run_number }}
        body: |
          Automatic build from:
          - Commit: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          - Date: ${{ github.event.head_commit.timestamp }}
        files: ${{ env.ZIP_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
