name: VS Build and Release

on:
  push:
    branches:
      - main
    paths:
      - '**.sln'
      - '**.vcxproj'
      - '**.cpp'
      - '**.h'
  workflow_dispatch:

env:
  SOLUTION_NAME: HappyEveningStudy.sln
  BUILD_CONFIG: Release
  PLATFORM: x64
  ZIP_NAME: HappyEveningStudy-${{ github.run_number }}.zip

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup VS 2022
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 17.0  # VS2022

    - name: Restore NuGet packages
      run: nuget restore "${{ env.SOLUTION_NAME }}"

    - name: Build Solution
      shell: pwsh
      run: |
        $artifactDir = "${{ github.workspace }}/artifacts"
        New-Item -Path $artifactDir -ItemType Directory -Force

        msbuild "${{ env.SOLUTION_NAME }}" `
          /p:Configuration=${{ env.BUILD_CONFIG }} `
          /p:Platform=${{ env.PLATFORM }} `
          /p:WindowsTargetPlatformVersion=10.0 `
          /p:OutDir="$artifactDir/"

    - name: Package artifacts
      shell: pwsh
      run: |
        $artifactDir = "${{ github.workspace }}/artifacts"
        $configFile = "${{ github.workspace }}/config.ini"
        
        # 复制配置文件
        Copy-Item $configFile -Destination $artifactDir
        
        # 创建ZIP包
        Compress-Archive -Path "$artifactDir/*" -DestinationPath "${{ env.ZIP_NAME }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-package
        path: ${{ env.ZIP_NAME }}

  release:
    needs: build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: release-package

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: "Build v${{ github.run_number }}"
        tag_name: v${{ github.run_number }}
        files: ${{ env.ZIP_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
